// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Must stay identical to android/app/google-services.json. These used to name
  // the old `scooterz-3d3c8` project while the backend sends FCM as `v-go-46d8c`
  // (Program.cs loads appdata/secrets/v-go-46d8c-firebase-adminsdk-*.json), and
  // FCM tokens are project-scoped — so every push to a rider silently went
  // nowhere. The captain app never had this bug because it calls a bare
  // Firebase.initializeApp(), which reads google-services.json directly.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIUxIjb4eN5U8D2A96nGh_pDx_V0GBJRg',
    appId: '1:1009005156907:android:f86288713a863a590c686e',
    messagingSenderId: '1009005156907',
    projectId: 'v-go-46d8c',
    storageBucket: 'v-go-46d8c.firebasestorage.app',
  );

  // iOS app "V-Go iOS" registered in v-go-46d8c (same project as Android, so
  // the backend's FCM credentials reach iPhones too).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAdUP1WhwQm7vBaFH7qIaWLG5JOkev_Q',
    appId: '1:1009005156907:ios:f7eddfc9b38c710d0c686e',
    messagingSenderId: '1009005156907',
    projectId: 'v-go-46d8c',
    storageBucket: 'v-go-46d8c.firebasestorage.app',
    iosBundleId: 'com.scooterapp.vgo',
  );
}
